# packages:
# library(RSelenium)
library(rvest)
library(stringi)
library(magrittr)
library(dplyr)
library(XML)
library(httr)
library(RCurl)
library(rjson)
library(xml2)
library(jsonlite)

# install text-mining packages:
# install.packages('readr')
# install.packages('wordcloud')
# install.packages('tm')
# install.packages('SnowballC')
# install.packages('RWeka')
# install.packages('RSentiment')
# install.packages('DT')
# install.packages('rJava')
# install.packages('stringr')
# install.packages("XML")
# install.packages("rjson")
# install.packages("RCurl")
